name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags
    branches:
      - '**'  # Triggers on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use a single runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Git Version
      id: version
      uses: codacy/git-version@2.5.4

    - name: Build
      run: |
        dotnet publish --configuration Release --runtime win-x64 --no-self-contained --output publish/magesfonttool-windows-amd64 src/MagesFontTool
        dotnet publish --configuration Release --runtime linux-x64 --no-self-contained --output publish/magesfonttool-linux-amd64 src/MagesFontTool
        pushd publish/magesfonttool-windows-amd64
        zip -r -j ../magesfonttool-windows-amd64.zip *
        popd
        pushd publish/magesfonttool-linux-amd64
        zip -r ../magesfonttool-linux-amd64.zip *
        popd

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          publish/magesfonttool-linux-amd64.zip
          publish/magesfonttool-windows-amd64.zip
        tag_name: ${{ steps.version.outputs.version }}.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
